// Code generated by go-swagger; DO NOT EDIT.

package call

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetCallsParams creates a new GetCallsParams object
// with the default values initialized.
func NewGetCallsParams() *GetCallsParams {
	var ()
	return &GetCallsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGetCallsParamsWithTimeout creates a new GetCallsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetCallsParamsWithTimeout(timeout time.Duration) *GetCallsParams {
	var ()
	return &GetCallsParams{

		timeout: timeout,
	}
}

// NewGetCallsParamsWithContext creates a new GetCallsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetCallsParamsWithContext(ctx context.Context) *GetCallsParams {
	var ()
	return &GetCallsParams{

		Context: ctx,
	}
}

// NewGetCallsParamsWithHTTPClient creates a new GetCallsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetCallsParamsWithHTTPClient(client *http.Client) *GetCallsParams {
	var ()
	return &GetCallsParams{
		HTTPClient: client,
	}
}

/*GetCallsParams contains all the parameters to send to the API endpoint
for the get calls operation typically these are written to a http.Request
*/
type GetCallsParams struct {

	/*AppID
	  Application ID.

	*/
	AppID *string
	/*Cursor
	  Cursor from previous response.next_cursor to begin results after, if any.

	*/
	Cursor *string
	/*FromTime
	  Unix timestamp in seconds, of call.created_at to begin the results at, default 0.

	*/
	FromTime *int64
	/*PerPage
	  Number of results to return, defaults to 30. Max of 100.

	*/
	PerPage *int64
	/*ToTime
	  Unix timestamp in seconds, of call.created_at to end the results at, defaults to latest.

	*/
	ToTime *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get calls params
func (o *GetCallsParams) WithTimeout(timeout time.Duration) *GetCallsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get calls params
func (o *GetCallsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get calls params
func (o *GetCallsParams) WithContext(ctx context.Context) *GetCallsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get calls params
func (o *GetCallsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get calls params
func (o *GetCallsParams) WithHTTPClient(client *http.Client) *GetCallsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get calls params
func (o *GetCallsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAppID adds the appID to the get calls params
func (o *GetCallsParams) WithAppID(appID *string) *GetCallsParams {
	o.SetAppID(appID)
	return o
}

// SetAppID adds the appId to the get calls params
func (o *GetCallsParams) SetAppID(appID *string) {
	o.AppID = appID
}

// WithCursor adds the cursor to the get calls params
func (o *GetCallsParams) WithCursor(cursor *string) *GetCallsParams {
	o.SetCursor(cursor)
	return o
}

// SetCursor adds the cursor to the get calls params
func (o *GetCallsParams) SetCursor(cursor *string) {
	o.Cursor = cursor
}

// WithFromTime adds the fromTime to the get calls params
func (o *GetCallsParams) WithFromTime(fromTime *int64) *GetCallsParams {
	o.SetFromTime(fromTime)
	return o
}

// SetFromTime adds the fromTime to the get calls params
func (o *GetCallsParams) SetFromTime(fromTime *int64) {
	o.FromTime = fromTime
}

// WithPerPage adds the perPage to the get calls params
func (o *GetCallsParams) WithPerPage(perPage *int64) *GetCallsParams {
	o.SetPerPage(perPage)
	return o
}

// SetPerPage adds the perPage to the get calls params
func (o *GetCallsParams) SetPerPage(perPage *int64) {
	o.PerPage = perPage
}

// WithToTime adds the toTime to the get calls params
func (o *GetCallsParams) WithToTime(toTime *int64) *GetCallsParams {
	o.SetToTime(toTime)
	return o
}

// SetToTime adds the toTime to the get calls params
func (o *GetCallsParams) SetToTime(toTime *int64) {
	o.ToTime = toTime
}

// WriteToRequest writes these params to a swagger request
func (o *GetCallsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.AppID != nil {

		// query param app_id
		var qrAppID string
		if o.AppID != nil {
			qrAppID = *o.AppID
		}
		qAppID := qrAppID
		if qAppID != "" {
			if err := r.SetQueryParam("app_id", qAppID); err != nil {
				return err
			}
		}

	}

	if o.Cursor != nil {

		// query param cursor
		var qrCursor string
		if o.Cursor != nil {
			qrCursor = *o.Cursor
		}
		qCursor := qrCursor
		if qCursor != "" {
			if err := r.SetQueryParam("cursor", qCursor); err != nil {
				return err
			}
		}

	}

	if o.FromTime != nil {

		// query param from_time
		var qrFromTime int64
		if o.FromTime != nil {
			qrFromTime = *o.FromTime
		}
		qFromTime := swag.FormatInt64(qrFromTime)
		if qFromTime != "" {
			if err := r.SetQueryParam("from_time", qFromTime); err != nil {
				return err
			}
		}

	}

	if o.PerPage != nil {

		// query param per_page
		var qrPerPage int64
		if o.PerPage != nil {
			qrPerPage = *o.PerPage
		}
		qPerPage := swag.FormatInt64(qrPerPage)
		if qPerPage != "" {
			if err := r.SetQueryParam("per_page", qPerPage); err != nil {
				return err
			}
		}

	}

	if o.ToTime != nil {

		// query param to_time
		var qrToTime int64
		if o.ToTime != nil {
			qrToTime = *o.ToTime
		}
		qToTime := swag.FormatInt64(qrToTime)
		if qToTime != "" {
			if err := r.SetQueryParam("to_time", qToTime); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
