// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	modelsv2 "github.com/fnproject/fn_go/modelsv2"
)

// DeleteAppsAppIDReader is a Reader for the DeleteAppsAppID structure.
type DeleteAppsAppIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAppsAppIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewDeleteAppsAppIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewDeleteAppsAppIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewDeleteAppsAppIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewDeleteAppsAppIDOK creates a DeleteAppsAppIDOK with default headers values
func NewDeleteAppsAppIDOK() *DeleteAppsAppIDOK {
	return &DeleteAppsAppIDOK{}
}

/*DeleteAppsAppIDOK handles this case with default header values.

Apps successfully deleted.
*/
type DeleteAppsAppIDOK struct {
}

func (o *DeleteAppsAppIDOK) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appID}][%d] deleteAppsAppIdOK ", 200)
}

func (o *DeleteAppsAppIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAppsAppIDNotFound creates a DeleteAppsAppIDNotFound with default headers values
func NewDeleteAppsAppIDNotFound() *DeleteAppsAppIDNotFound {
	return &DeleteAppsAppIDNotFound{}
}

/*DeleteAppsAppIDNotFound handles this case with default header values.

App does not exist.
*/
type DeleteAppsAppIDNotFound struct {
	Payload *modelsv2.Error
}

func (o *DeleteAppsAppIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appID}][%d] deleteAppsAppIdNotFound  %+v", 404, o.Payload)
}

func (o *DeleteAppsAppIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(modelsv2.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteAppsAppIDDefault creates a DeleteAppsAppIDDefault with default headers values
func NewDeleteAppsAppIDDefault(code int) *DeleteAppsAppIDDefault {
	return &DeleteAppsAppIDDefault{
		_statusCode: code,
	}
}

/*DeleteAppsAppIDDefault handles this case with default header values.

Unexpected error
*/
type DeleteAppsAppIDDefault struct {
	_statusCode int

	Payload *modelsv2.Error
}

// Code gets the status code for the delete apps app ID default response
func (o *DeleteAppsAppIDDefault) Code() int {
	return o._statusCode
}

func (o *DeleteAppsAppIDDefault) Error() string {
	return fmt.Sprintf("[DELETE /apps/{appID}][%d] DeleteAppsAppID default  %+v", o._statusCode, o.Payload)
}

func (o *DeleteAppsAppIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(modelsv2.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
