// Code generated by go-swagger; DO NOT EDIT.

package apps

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	modelsv2 "github.com/fnproject/fn_go/modelsv2"
)

// GetAppsAppIDReader is a Reader for the GetAppsAppID structure.
type GetAppsAppIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAppsAppIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetAppsAppIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 404:
		result := NewGetAppsAppIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		result := NewGetAppsAppIDDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetAppsAppIDOK creates a GetAppsAppIDOK with default headers values
func NewGetAppsAppIDOK() *GetAppsAppIDOK {
	return &GetAppsAppIDOK{}
}

/*GetAppsAppIDOK handles this case with default header values.

App details and stats.
*/
type GetAppsAppIDOK struct {
	Payload *modelsv2.App
}

func (o *GetAppsAppIDOK) Error() string {
	return fmt.Sprintf("[GET /apps/{appID}][%d] getAppsAppIdOK  %+v", 200, o.Payload)
}

func (o *GetAppsAppIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(modelsv2.App)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAppsAppIDNotFound creates a GetAppsAppIDNotFound with default headers values
func NewGetAppsAppIDNotFound() *GetAppsAppIDNotFound {
	return &GetAppsAppIDNotFound{}
}

/*GetAppsAppIDNotFound handles this case with default header values.

App does not exist.
*/
type GetAppsAppIDNotFound struct {
	Payload *modelsv2.Error
}

func (o *GetAppsAppIDNotFound) Error() string {
	return fmt.Sprintf("[GET /apps/{appID}][%d] getAppsAppIdNotFound  %+v", 404, o.Payload)
}

func (o *GetAppsAppIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(modelsv2.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetAppsAppIDDefault creates a GetAppsAppIDDefault with default headers values
func NewGetAppsAppIDDefault(code int) *GetAppsAppIDDefault {
	return &GetAppsAppIDDefault{
		_statusCode: code,
	}
}

/*GetAppsAppIDDefault handles this case with default header values.

Unexpected error
*/
type GetAppsAppIDDefault struct {
	_statusCode int

	Payload *modelsv2.Error
}

// Code gets the status code for the get apps app ID default response
func (o *GetAppsAppIDDefault) Code() int {
	return o._statusCode
}

func (o *GetAppsAppIDDefault) Error() string {
	return fmt.Sprintf("[GET /apps/{appID}][%d] GetAppsAppID default  %+v", o._statusCode, o.Payload)
}

func (o *GetAppsAppIDDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(modelsv2.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
