// Code generated by go-swagger; DO NOT EDIT.

package modelsv2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// AppID opaque, unique application identifier
// swagger:model AppID
type AppID string

// Validate validates this app ID
func (m AppID) Validate(formats strfmt.Registry) error {
	return nil
}
