// Code generated by go-swagger; DO NOT EDIT.

package modelsv2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// FnID opaque, unique function identifier
// swagger:model FnID
type FnID string

// Validate validates this fn ID
func (m FnID) Validate(formats strfmt.Registry) error {
	return nil
}
