// Code generated by go-swagger; DO NOT EDIT.

package modelsv2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// NextCursor cursor to send with subsequent request to receive the next page, if non-empty
// swagger:model nextCursor
type NextCursor string

// Validate validates this next cursor
func (m NextCursor) Validate(formats strfmt.Registry) error {
	return nil
}
