// Code generated by go-swagger; DO NOT EDIT.

package modelsv2

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
)

// TriggerID opaque, unique trigger identifier
// swagger:model TriggerID
type TriggerID string

// Validate validates this trigger ID
func (m TriggerID) Validate(formats strfmt.Registry) error {
	return nil
}
